//! Integration test for the built-in synthetic RT study generator and the
//! loader: the study is generated by `gen_test_data` into a scratch folder
//! under `target/`, then read back through the normal loading path.

use std::path::PathBuf;
use std::sync::OnceLock;

use rust_dicom_viewer::gen_test_data::{self, GenParams};
use rust_dicom_viewer::geometry::Vec3;
use rust_dicom_viewer::loader::{self, Progress};
use rust_dicom_viewer::render;
use rust_dicom_viewer::volume::ViewPlane;

/// Generate the canonical (default-parameter) study once per test binary.
fn test_data_dir() -> &'static PathBuf {
    static DIR: OnceLock<PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/test_data_synth");
        let _ = std::fs::remove_dir_all(&dir);
        let n = gen_test_data::generate(&dir, &GenParams::default(), &Progress::default())
            .expect("test data generation succeeds");
        assert_eq!(n, 40 + 3 + 4, "CT slices + RS/RP/RD + 4 extras");
        dir
    })
}

#[test]
fn load_synthetic_study() {
    let dir = test_data_dir();
    let progress = Progress::default();
    let t0 = std::time::Instant::now();
    let study = loader::load_directory(dir, &progress).expect("study should load");
    eprintln!("loaded in {:?}; warnings: {:?}", t0.elapsed(), study.warnings);

    // ---- Volume ----
    let v = &study.volume;
    assert_eq!(v.dims, [96, 96, 40], "volume dims");
    assert!((v.spacing[0] - 2.0).abs() < 1e-6);
    assert!((v.spacing[1] - 2.0).abs() < 1e-6);
    assert!((v.spacing[2] - 2.0).abs() < 1e-3, "slice spacing {}", v.spacing[2]);

    // Patient (0,0,0) is the center of the target sphere (HU 100).
    let c = v.patient_to_voxel(Vec3::ZERO);
    assert!((c[0] - 47.5).abs() < 1e-6 && (c[1] - 47.5).abs() < 1e-6 && (c[2] - 19.5).abs() < 1e-3);
    let hu_center = v.index(48, 48, 20);
    assert_eq!(hu_center, 100, "target HU");
    let hu_air = v.index(2, 2, 20);
    assert_eq!(hu_air, -1000, "air HU");
    // Water shell inside body but outside target.
    let w = v.patient_to_voxel(Vec3::new(50.0, 0.0, 1.0));
    let hu_water = v.index(w[0].round() as usize, w[1].round() as usize, w[2].round() as usize);
    assert_eq!(hu_water, 0, "water HU");

    // Round-trip mapping.
    let p = v.voxel_to_patient(10.0, 20.0, 30.0);
    let back = v.patient_to_voxel(p);
    assert!((back[0] - 10.0).abs() < 1e-9 && (back[1] - 20.0).abs() < 1e-9 && (back[2] - 30.0).abs() < 1e-9);

    // ---- Structures ----
    let ss = study.structure_sets.first().expect("RTSTRUCT present");
    assert_eq!(ss.rois.len(), 3);
    let target = ss.rois.iter().find(|r| r.name == "TARGET").expect("TARGET roi");
    assert_eq!(target.roi_type, "PTV");
    assert!(target.contours.len() >= 20, "target contour count {}", target.contours.len());
    let body = ss.rois.iter().find(|r| r.name == "BODY").unwrap();
    assert_eq!(body.contours.len(), 40);

    // Axial contour of TARGET on the central slice must be a circle of r≈25 mm.
    let gfx = render::roi_on_plane(v, target, ViewPlane::Axial, 20);
    assert!(!gfx.polylines.is_empty(), "target polyline on central axial slice");
    let pl = &gfx.polylines[0];
    let r_mm: f32 = pl
        .iter()
        .map(|p| {
            let pat = v.voxel_to_patient(p[0] as f64, p[1] as f64, 20.0);
            ((pat.x * pat.x + pat.y * pat.y) as f32).sqrt()
        })
        .sum::<f32>()
        / pl.len() as f32;
    assert!((r_mm - 24.97).abs() < 1.0, "target radius on central slice: {r_mm}");

    // Sagittal silhouette segments should exist through the target center.
    let gfx_sag = render::roi_on_plane(v, target, ViewPlane::Sagittal, 48);
    assert!(!gfx_sag.segments.is_empty(), "sagittal silhouette");

    // ---- Dose ----
    assert_eq!(study.doses.len(), 1);
    let d = &study.doses[0];
    assert!((d.max_dose - 60.0).abs() < 0.5, "max dose {}", d.max_dose);
    let center = d.sample(Vec3::ZERO).expect("dose at isocenter");
    assert!((center - 60.0).abs() < 0.6, "isocenter dose {center}");
    // 1 sigma away along x: 60 * exp(-0.5) ≈ 36.39
    let one_sigma = d.sample(Vec3::new(20.0, 0.0, 0.0)).unwrap();
    assert!((one_sigma - 36.39).abs() < 1.0, "1-sigma dose {one_sigma}");
    assert!(d.sample(Vec3::new(500.0, 0.0, 0.0)).is_none(), "outside grid");

    // Dose plane resampling + isodose extraction on the central axial slice.
    let mut plane = Vec::new();
    render::sample_dose_plane(v, d, ViewPlane::Axial, 20, &mut plane);
    let max_in_plane = plane.iter().copied().fold(0.0f32, f32::max);
    assert!((max_in_plane - 60.0).abs() < 1.5, "max in plane {max_in_plane}");
    let segs = render::marching_squares(&plane, 96, 96, 30.0);
    assert!(segs.len() > 20, "50% isodose segments: {}", segs.len());
    // The 50% (30 Gy) isodose of a sigma-20 Gaussian lies at r = 20*sqrt(2 ln 2) ≈ 23.55 mm.
    let mean_r: f32 = segs
        .iter()
        .map(|(a, _)| {
            let pat = v.voxel_to_patient(a[0] as f64, a[1] as f64, 20.0);
            ((pat.x * pat.x + pat.y * pat.y) as f32).sqrt()
        })
        .sum::<f32>()
        / segs.len() as f32;
    assert!((mean_r - 23.55).abs() < 1.5, "50% isodose radius {mean_r}");

    // ---- Plan ----
    assert_eq!(study.plans.len(), 1);
    let plan = &study.plans[0];
    assert_eq!(plan.plan_kind, "Ion");
    assert_eq!(plan.n_fractions, Some(30));
    assert!((plan.target_prescription_dose.unwrap() - 60.0).abs() < 1e-6);
    assert_eq!(plan.beams.len(), 2);
    let b1 = &plan.beams[0];
    assert_eq!(b1.radiation_type, "PROTON");
    assert_eq!(b1.n_control_points, 4);
    assert!((b1.energy_min.unwrap() - 120.0).abs() < 1e-6);
    assert!((b1.energy_max.unwrap() - 180.0).abs() < 1e-6);
    assert_eq!(b1.isocenter.unwrap(), Vec3::ZERO);
    assert!((b1.meterset.unwrap() - 120.5).abs() < 1e-6);
    let b2 = &plan.beams[1];
    assert!((b2.gantry_angle.unwrap() - 90.0).abs() < 1e-6);

    // ---- Planar images (DX + RTIMAGE) ----
    assert_eq!(study.planar_images.len(), 2, "DX + RTIMAGE expected");
    let dx = study
        .planar_images
        .iter()
        .find(|p| p.modality == "DX")
        .expect("DX image");
    assert_eq!((dx.rows, dx.cols), (400, 512));
    assert!(dx.max_value > dx.min_value);
    let rti = study
        .planar_images
        .iter()
        .find(|p| p.modality == "RTIMAGE")
        .expect("RTIMAGE");
    assert_eq!(rti.label, "DRR_G000");
    assert!(rti.info.iter().any(|(k, v)| k == "Machine" && v == "SYNTH-PBS"));
    assert!(rti.info.iter().any(|(k, _)| k == "SAD"));

    // ---- REG spatial registration ----
    assert_eq!(study.registrations.len(), 1);
    let reg = &study.registrations[0];
    assert!(!reg.deformable);
    assert_eq!(reg.items.len(), 2);
    assert!(reg.items[0].is_identity);
    let item = &reg.items[1];
    assert!(!item.is_identity);
    assert_eq!(item.matrix_type, "RIGID");
    let rigid = rust_dicom_viewer::extras::matrix_to_rigid(&item.matrix, false)
        .expect("rigid conversion");
    let mapped = rigid.map(Vec3::new(1.0, 2.0, 3.0));
    assert!(
        (mapped - Vec3::new(13.0, -7.0, 3.0)).length() < 1e-6,
        "REG matrix maps by (12,-9,0): got {mapped:?}"
    );
    let inv = rust_dicom_viewer::extras::matrix_to_rigid(&item.matrix, true).unwrap();
    assert!((inv.map(mapped) - Vec3::new(1.0, 2.0, 3.0)).length() < 1e-6, "inverted REG");

    // ---- RTRECORD ----
    assert_eq!(study.treat_records.len(), 1);
    let rec = &study.treat_records[0];
    assert!(rec.ion);
    assert_eq!(rec.fraction, Some(5));
    assert_eq!(rec.machine, "SYNTH-PBS");
    assert_eq!(rec.beams.len(), 2);
    let rb = &rec.beams[0];
    assert_eq!(rb.name, "G000");
    assert!((rb.specified_meterset.unwrap() - 120.5).abs() < 1e-6);
    assert!((rb.delivered_meterset.unwrap() - 120.3).abs() < 1e-6);
    assert_eq!(rb.termination_status, "NORMAL");

    // ---- Slice extraction sanity ----
    let mut buf = Vec::new();
    v.extract_slice(ViewPlane::Axial, 20, &mut buf);
    assert_eq!(buf.len(), 96 * 96);
    assert_eq!(buf[48 * 96 + 48], 100);
    v.extract_slice(ViewPlane::Sagittal, 48, &mut buf);
    assert_eq!(buf.len(), 96 * 40);
    // Sagittal row for k=20 is displayed at y = (nz-1) - 20 = 19; target center j=48.
    assert_eq!(buf[19 * 96 + 48], 100);
    v.extract_slice(ViewPlane::Coronal, 48, &mut buf);
    assert_eq!(buf.len(), 96 * 40);
    assert_eq!(buf[19 * 96 + 48], 100);
}

#[test]
fn perf_smoke() {
    let dir = test_data_dir();
    let progress = Progress::default();
    let study = loader::load_directory(dir, &progress).unwrap();
    let v = &study.volume;
    let d = &study.doses[0];

    let mut buf = Vec::new();
    let t = std::time::Instant::now();
    for _ in 0..200 {
        v.extract_slice(ViewPlane::Sagittal, 48, &mut buf);
    }
    eprintln!("sagittal slice extraction: {:?} / slice", t.elapsed() / 200);

    let mut plane = Vec::new();
    let t = std::time::Instant::now();
    for _ in 0..50 {
        render::sample_dose_plane(v, d, ViewPlane::Axial, 20, &mut plane);
    }
    eprintln!("dose plane resample: {:?} / slice", t.elapsed() / 50);
}

/// The generator's parameters must actually move the phantom, the dose peak
/// and the plan isocenter together, and `extras: false` must suppress the
/// DX / RTIMAGE / REG / RTRECORD objects.
#[test]
fn generator_parameters_shift_the_phantom() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/test_data_shifted");
    let _ = std::fs::remove_dir_all(&dir);
    let params = GenParams {
        target_shift_y: 8.0,
        shift_x: 10.0,
        shift_y: -6.0,
        peak: 45.0,
        plan_label: "ShiftedPhantom".into(),
        reg_shift: [1.0, 2.0, 3.0],
        extras: false,
    };
    let n = gen_test_data::generate(&dir, &params, &Progress::default())
        .expect("generation succeeds");
    assert_eq!(n, 40 + 3, "CT slices + RS/RP/RD, no extras");

    let study = loader::load_directory(&dir, &Progress::default()).expect("loads");
    // Target center is now at (shift_x, target_shift_y + shift_y, 0).
    let center = Vec3::new(10.0, 2.0, 0.0);
    let idx = study.volume.patient_to_voxel(center);
    let hu = study.volume.index(
        idx[0].round() as usize,
        idx[1].round() as usize,
        idx[2].round() as usize,
    );
    assert_eq!(hu, 100, "target HU at the shifted center");
    // …while the old center now sits in plain water.
    let old = study.volume.patient_to_voxel(Vec3::new(0.0, -40.0, 0.0));
    assert_eq!(
        study.volume.index(
            old[0].round() as usize,
            old[1].round() as usize,
            old[2].round() as usize
        ),
        0,
        "water away from the shifted target"
    );

    let dose = study.doses[0].sample(center).expect("dose at the shifted peak");
    assert!((dose - 45.0).abs() < 1.0, "peak dose {dose}");

    let plan = &study.plans[0];
    assert_eq!(plan.label, "ShiftedPhantom");
    assert!((plan.target_prescription_dose.unwrap() - 45.0).abs() < 1e-6);
    assert_eq!(plan.beams[0].isocenter.unwrap(), center);

    let target = study
        .structure_sets
        .first()
        .unwrap()
        .rois
        .iter()
        .find(|r| r.name == "TARGET")
        .unwrap();
    let p0 = target.contours[target.contours.len() / 2].points[0];
    assert!(
        ((p0.x - 10.0).hypot(p0.y - 2.0) - 25.0).abs() < 1.5,
        "contour radius around the shifted center: {p0:?}"
    );

    assert!(study.planar_images.is_empty(), "no DX / RTIMAGE");
    assert!(study.registrations.is_empty(), "no REG");
    assert!(study.treat_records.is_empty(), "no RTRECORD");

    let _ = std::fs::remove_dir_all(&dir);
}

/// A patient folder with several RTSTRUCT files (e.g. one per 4DCT phase)
/// must load *all* of them, each with its referenced-series link intact.
#[test]
fn multiple_structure_sets_are_all_loaded() {
    let dir = test_data_dir();
    // Duplicate the structure set to imitate a second per-phase RTSTRUCT.
    let multi = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/test_data_multi_rs");
    let _ = std::fs::remove_dir_all(&multi);
    std::fs::create_dir_all(&multi).unwrap();
    for e in std::fs::read_dir(dir).unwrap() {
        let e = e.unwrap();
        std::fs::copy(e.path(), multi.join(e.file_name())).unwrap();
    }
    std::fs::copy(multi.join("RS_synth.dcm"), multi.join("RS_synth_phase2.dcm")).unwrap();

    let study = loader::load_directory(&multi, &Progress::default()).expect("loads");
    assert_eq!(study.structure_sets.len(), 2, "both RTSTRUCTs loaded");
    for ss in &study.structure_sets {
        assert_eq!(ss.rois.len(), 3);
        assert!(!ss.sop_instance_uid.is_empty());
        assert!(!ss.referenced_series_uid.is_empty());
        // The reference must point at the CT series that exists in the tree.
        assert!(
            study.series.iter().any(|se| se.uid == ss.referenced_series_uid),
            "referenced series present in the study tree"
        );
    }
    // No "using first file" warning anymore.
    assert!(
        !study.warnings.iter().any(|w| w.contains("RTSTRUCT files found")),
        "no discard warning: {:?}",
        study.warnings
    );
    // Dose ▶ plan and plan ▶ structures links resolve.
    let d = &study.doses[0];
    assert!(!d.referenced_plan_uid.is_empty());
    let plan = study
        .plans
        .iter()
        .find(|p| p.sop_instance_uid == d.referenced_plan_uid)
        .expect("dose references the plan");
    assert!(!plan.referenced_structset_uid.is_empty());
    assert!(
        study
            .structure_sets
            .iter()
            .any(|ss| ss.sop_instance_uid == plan.referenced_structset_uid),
        "plan references a loaded structure set"
    );
    let _ = std::fs::remove_dir_all(&multi);
}
